version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    environment:
      - PLY_ENV=test
      - MONGO_URL=mongodb://mongodb:27017

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 